name: Download and Upload to Releases

on:
  workflow_dispatch:          # you can trigger this manually from the Actions tab
    inputs:
      download_url:
        description: 'Download URL of the mp4/mp3'
        required: true

      media_type:
        description: 'Whether mp3/mp4'
        required: true

      file_name:
        description: 'The name of the file'
        required: true

      tag_id:
        description: 'Tag name'
        required: true
      

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install wget curl -y

      - name: Download the respective media
        run: mkdir dn && wget -O dn/file.${{ inputs.media_type }} ${{ inputs.download_url }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_id }}
          name: "${{ inputs.file_name }}"
          body: "Downloaded from ${{ inputs.download_url }}"
          files: dn/file.${{ inputs.media_type }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
